# Generated by Django 5.0.6 on 2024-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=100, verbose_name="user_email"),
                ),
                (
                    "user_password",
                    models.CharField(max_length=120, verbose_name="user_password"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=60, verbose_name="user_name"),
                ),
            ],
            options={
                "db_table": "Users",
            },
        ),
    ]
