# Generated by Django 5.0.6 on 2024-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe_id",
                    models.CharField(max_length=100, verbose_name="recipe_id"),
                ),
            ],
            options={
                "db_table": "Recipe",
            },
        ),
    ]
