# Generated by Django 5.0.6 on 2024-06-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=100, verbose_name="item_name"),
                ),
            ],
            options={
                "db_table": "Item",
            },
        ),
    ]
