# Generated by Django 5.0.6 on 2024-06-07 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_item_new_alter_new_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="New",
            new_name="Item",
        ),
        migrations.AlterModelTable(
            name="item",
            table="Item",
        ),
    ]
