# Generated by Django 5.0.6 on 2024-06-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_fridge_items_publish_recipes_delete_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="id",
        ),
        migrations.AddField(
            model_name="items",
            name="it_id",
            field=models.IntegerField(
                default="invalid",
                primary_key=True,
                serialize=False,
                verbose_name="it_id",
            ),
        ),
    ]
