# Generated by Django 5.0.6 on 2024-06-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_items_id_items_it_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="publish",
            name="pub_re_id",
            field=models.ForeignKey(
                default="none",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.recipes",
            ),
        ),
    ]
