# Generated by Django 5.0.6 on 2024-06-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_recipes_re_minute_alter_recipes_re_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="fk_recipes_publisher",
            field=models.ForeignKey(
                default="admin",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.users",
            ),
        ),
    ]
