# Generated by Django 5.0.6 on 2024-06-08 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_recipes_fk_recipes_publisher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="fk_recipes_publisher",
        ),
    ]
